import anndata as ad
import scanpy as sc
from sklearn.metrics import adjusted_rand_score

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_solution': 'resources_test/common/2023_yao_mouse_brain_scrnaseq_10xv2/dataset.h5ad',
  'input_prediction': 'resources_test/task_spatial_segmentation/mouse_brain_combined/output_scrnaseq_reference.h5ad',
  'output': 'output.h5ad',
  'label': None
}
meta = {
  'name': 'ari'
}
## VIASH END

print('>> Reading input files', flush=True)
input_solution = ad.read_h5ad(par['input_solution'])
input_prediction = ad.read_h5ad(par['input_prediction'])

assert (input_prediction.obs_names == input_solution.obs_names).all(), "obs_names not the same in prediction and solution inputs"

if not par['label']:
  print('>> Postprocessing for metric', flush=True)
  seed= 123
  sc.pp.neighbors(input_solution, n_neighbors=20, random_state=seed)
  sc.tl.umap(input_solution, min_dist=0.1, spread=1.2, random_state=seed)
  sc.tl.leiden(input_solution, resolution=1.0, key_added='leiden', random_state=seed)

  sc.pp.neighbors(input_prediction, n_neighbors=20, random_state=seed)
  sc.tl.umap(input_prediction, min_dist=0.1, spread=1.2, random_state=seed)
  sc.tl.leiden(input_prediction, resolution=1.0, key_added='leiden', random_state=seed)

print('>> Compute metrics', flush=True)
uns_metric_ids = [ 'ari' ]
uns_metric_values = adjusted_rand_score(input_solution.obs["label"], input_prediction.obs["label_pred"])

print(">> Write output AnnData to file", flush=True)
output = ad.AnnData(
  uns={
    'dataset_id': input_prediction.uns['dataset_id'],
    'normalization_id': input_prediction.uns['normalization_id'],
    'method_id': input_prediction.uns['method_id'],
    'metric_ids': uns_metric_ids,
    'metric_values': uns_metric_values
  }
)
output.write_h5ad(par['output'], compression='gzip')
