
import anndata as ad
import scanpy as sc
from sklearn.metrics import adjusted_rand_score

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_scrnaseq_reference': 'resources_test/task_spatial_segmentation/mouse_brain_combined/reference_prediction.h5ad',
  'input_prediction': 'resources_test/task_spatial_segmentation/mouse_brain_combined/method_prediction.h5ad',
  'output': 'resources_test/task_spatial_segmentation/mouse_brain_combined/score.h5ad',
  'label': 'cell_type'
}
meta = {
  'name': 'ari'
}
## VIASH END

print('>> Reading input files', flush=True)
input_scrnaseq_reference = ad.read_h5ad(par['input_scrnaseq_reference'])
input_prediction = ad.read_h5ad(par['input_prediction'])

assert (input_prediction.obs_names == input_scrnaseq_reference.obs_names).all(), "obs_names not the same in prediction and solution inputs"
  
print('>> Compute metrics', flush=True)
uns_metric_ids = [ 'ari' ]
uns_metric_values = adjusted_rand_score(input_scrnaseq_reference.obs[par['label']], input_prediction.obs[par['label']])

print(">> Write output AnnData to file", flush=True)
output = ad.AnnData(
  uns={
    'dataset_id': input_prediction.uns['dataset_id'],
    'normalization_id': input_prediction.uns['normalization_id'],
    # 'method_id': input_prediction.uns['method_id'], #TODO
    'metric_ids': uns_metric_ids,
    'metric_values': uns_metric_values
  }
)
output.write_h5ad(par['output'], compression='gzip')
